const config = {
  googleFormLink: ``,
  title: `Baarik Leads Form`,
  description: `you add new leads here.`,
  fields: [
    {
      id: `number`,
      elementType: "input",
      googleFormName: `entry.1`,
      props: {
        validationfunction: () => true,
        placeholder: `Phone Number`,
        required: true,
        // defaultValue: "",
        type: `tel`,
        variant: "standard",
        label: "Phone Number",
      },
    },
    {
      id: `clickedAdd`,
      elementType: "input",
      googleFormName: `entry.2`,
      props: {
        validationfunction: () => true,
        required: true,
        type: `select`,
        label: "Clicked Add",
        options: [
          { value: `Add_1`, label: `ADD 1` },
          { value: `Add_2`, label: `ADD 2` },
        ],
        // DropdownClassName: "",
        showClearOption: true,
        // DropdownItemClassName: "",
      },
    },
    {
      id: `name`,
      elementType: "input",
      googleFormName: `entry.3`,
      props: {
        validationfunction: () => true,
        placeholder: `Name`,
        required: true,
        defaultValue: "Unknown",
        type: `text`,
        variant: "standard",
        label: "Name",
      },
    },
    {
      id: "group_1",
      elementType: "group",
      props: {
        isOpen: null,
        setIsOpen: null,

        buttonText: { onOpen: "Close", onClose: "Open" },
        buttonIcon: null,
        rotateIcon: false,
        buttonOnClick: null,
        buttonClassName: "",
        ButtonOnOpenClassName: "",
        ButtonOnCloseClassName: "",
        buttonColor: null,
        outline: true,

        containerClassName: "",
        containerOnOpenClassName: "opacity-100",
        containerOnCloseClassName: "opacity-0",
        containerAfterCloseClassName: "hidden",
        containerBeforeOpenClassName: "",

        duration: 300,

        // optional: if you want to provide your own id for aria-controls
        contentId: null,
      },
      fields: [
        {
          id: `company`,
          elementType: "input",
          googleFormName: `entry.4`,
          props: {
            validationfunction: () => true,
            placeholder: `Company Name`,
            // required: true,
            // defaultValue: "Unknown",
            type: `text`,
            variant: "standard",
            label: "Company Name",
          },
        },
        {
          id: `email`,
          elementType: "input",
          googleFormName: `entry.5`,
          props: {
            validationfunction: () => true,
            placeholder: `Email`,
            // required: true,
            // defaultValue: "Unknown",
            type: `email`,
            variant: "standard",
            label: "Email",
          },
        },
        {
          id: `website`,
          elementType: "input",
          googleFormName: `entry.6`,
          props: {
            validationfunction: () => true,
            placeholder: `Website`,
            // required: true,
            // defaultValue: "Unknown",
            type: `url`,
            variant: "standard",
            label: "Website",
          },
        },
        {
          id: `address`,
          elementType: "input",
          googleFormName: `entry.7`,
          props: {
            validationfunction: () => true,
            placeholder: `Address`,
            // required: true,
            // defaultValue: "Unknown",
            type: `text`,
            variant: "standard",
            label: "Address",
          },
        },
        {
          id: `disposition`,
          elementType: "input",
          googleFormName: `entry.8`,
          props: {
            validationfunction: () => true,
            required: true,
            type: `select`,
            label: "Disposition",
            options: [
              { value: `Disposition_1`, label: `Disposition 1` },
              { value: `Disposition_2`, label: `Disposition 2` },
            ],
            // DropdownClassName: "",
            showClearOption: true,
            // DropdownItemClassName: "",
          },
        },
        {
          id: `extraInfo`,
          elementType: "input",
          googleFormName: `entry.9`,
          props: {
            validationfunction: () => true,
            placeholder: `Extra Info`,
            // required: true,
            // defaultValue: "Unknown",
            type: `textarea`,
            variant: "standard",
            label: "Extra Info",
          },
        },
        {
          id: `agentName`,
          elementType: "input",
          googleFormName: `entry.10`,
          props: {
            validationfunction: () => true,
            placeholder: `Agent Name`,
            // required: true,
            defaultValue: "walid",
            type: `text`,
            variant: "standard",
            label: "Agent Name",
          },
        },
      ],
    },
  ],
};

export default config;
